### ISSUE TITLE
BOM causes error message to include entire file

### ISSUE THREAD

**Issue by mexezero** [netplex/json-smart-v2#13]
Normally when parsing a JSON file the message is, for example:
```
Unexpected token ({) at position 50
```
But if a byte order mark is found as the first character on the first line, the "unexpected token" that gets printed out is the entire file and the position printed is the very last position of the file.

**Comment by aborg0** [comment]
Probably wrapping the inputstream with [BOMInputStream](http://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/input/BOMInputStream.html) would be a good workaround.

**Comment by UrielCh** [comment]
you have to filter BOM yourself.
this is not an issue.
