### ISSUE TITLE
Parsing a string does not maintain attribute order and is limited to 130 attributes 

### ISSUE THREAD

**Issue by javierpajaro** [netplex/json-smart-v2#14]
Hi Uriel,

Parsing a string containing a json object does not maintain attribute order and is limited to 130 attributes.

Is there any way to handle this via configuration? 

Thanks, Javier.

**Comment by UrielCh** [comment]
1st there is no attributes limits.
2nd you can preserved attributes order using LinkedHashMap

**Comment by javierpajaro** [comment]
@UrielCh are you thinking to deliver a release using LinkedHashMap ?
