### ISSUE TITLE
Character U+007F in string is not accepted in MODE_RFC4627

### ISSUE THREAD

**Issue by zline** [netplex/json-smart-v2#18]
`new JSONParser(JSONParser.MODE_RFC4627).parse(String.format("[\"%c\"]", 127));` throws exception, but expected behavior is to return array containing string of one character (unicode codepoint 127).

According to RFC: 
>   All Unicode characters may be placed within the
>   quotation marks except for the characters that must be escaped:
>   quotation mark, reverse solidus, and the control characters (U+0000
>   through U+001F).

**Comment by UrielCh** [comment]
unicode 127 codepoint is the DELETE char, so it's a control character.

so this is the correct behaviour.

**Comment by zline** [comment]
Does range "U+0000 through U+001F" contain U+007F? See quote from RFC.

**Comment by UrielCh** [comment]
let me check that twice ...
