### ISSUE TITLE
java.lang.UnsupportedOperationException: can't load this type of class file

### ISSUE THREAD

**Issue by sidleciel** [netplex/json-smart-v2#23]
on Andriod's environment
when call [String s = net.minidev.json.JSONValue.toJSONString(person);] . throw following error:

W/System.err: java.lang.UnsupportedOperationException: can't load this type of class file
W/System.err:     at java.lang.ClassLoader.defineClass(ClassLoader.java:265)
W/System.err:     at net.minidev.asm.DynamicClassLoader.defineClass(DynamicClassLoader.java:86)
W/System.err:     at net.minidev.asm.BeansAccessBuilder.bulid(BeansAccessBuilder.java:313)
W/System.err:     at net.minidev.asm.BeansAccess.get(BeansAccess.java:111)
W/System.err:     at net.minidev.json.reader.BeansWriterASM.writeJSONString(BeansWriterASM.java:17)
W/System.err:     at net.minidev.json.JSONValue.writeJSONString(JSONValue.java:596)
W/System.err:     at net.minidev.json.JSONValue.toJSONString(JSONValue.java:632)
W/System.err:     at net.minidev.json.JSONValue.toJSONString(JSONValue.java:610)

**Comment by UrielCh** [comment]
I think that json-smart V2 is not compatible with android.
only the V1 is compatible.

**Comment by pling2mobileiron** [comment]
Any information about why this is not support for Android?
