### ISSUE TITLE
Where is the @JsonProperty annotation ?

### ISSUE THREAD

**Issue by fabienrenaud** [netplex/json-smart-v2#26]
Some json fields are not nice or impossible to write in POJOs. For instance:

```
{"_id": "theid" }
{"200": "the200" }
```

usually, json framworks provides annotations to specify the name of the json property. for instance:

```
public class ThePojo { @JsonProperty("_id") public String id; }
```

Where is this feature in json-smart?

**Comment by UrielCh** [comment]
Sorry havent implement the @JsonProperty().

for that purpose, I use the function like that:
JSONValue.remapField(ApiModel.class, "enum", "enum_");
JSONValue.remapField(ApiModel.class, "default", "default_");
JSONValue.remapField(ApiModel.class, "200", "field200");

class ApiModel {
 public String enum_;
 public String default_;
 public String field200;
}

**Comment by fabienrenaud** [comment]
Ok.

I wrote a jmh benchmark comparing a lot of json libs (including json-smart)... that's when I ran into this issue with _id.
https://github.com/fabienrenaud/java-json-benchmark

json-smart did pretty well.
better than gson.

**Comment by UrielCh** [comment]
thx and sorry for the delay.

**Comment by UrielCh** [comment]
I have just look at your benchmark.

maybe you should also add some API testing.
take those JSON messages:
https://code.google.com/archive/p/json-smart/wikis/FeaturesTests.wiki
to test all the APIs.
beeing fast is good, but returning the good result is better.

you can also add som truncated JSON message :) like:
{"a": "\u22"}
{"a": "text
