### ISSUE TITLE
Last project update on 2021-05-02, New maintainer needed.

### ISSUE THREAD

**Issue by burtonator** [netplex/json-smart-v2#36]
I think this project may be unmaintained now.  The last commit was over a year ago.  Additionally, there are some critical bugs that need to be fixed. 

If someone wants to setup up and help maintain it and cut releases I think everyone would appreciate it (but I don't have time)

**Comment by UrielCh** [comment]
Since I move to California, maintains and upgrade json-smart became more difficult.

I have just get back my GPG key, and release version 2.3.

**Comment by pmouawad** [comment]
Thanks for your work @UrielCh !

**Comment by UrielCh** [comment]
If you need some patch and new releases open your PR now.

**Comment by goughy000** [comment]
Are you still looking for a new maintainer @UrielCh ?

**Comment by UrielCh** [comment]
the issue is pin... so yes....

**Comment by Shoothzj** [comment]
@UrielCh I want to help maintain this project, with some bug fix and cut releases.

**Comment by UrielCh** [comment]
Since at least one of your PR had been accepted, You get the deal.
