### ISSUE TITLE
Is json-smart 2.2.1 compatible with json-smart-1.1.1?

### ISSUE THREAD

**Issue by ymohdriz** [netplex/json-smart-v2#42]
Hi team,

In out project, we have used the json-smart-1.1.1. We need to use Json-path 2.2.0 which is compatible with json-smart 2.2.1 but not with json-smart-1.1.1.

We have to update the json-smart-1.1.1 to json-smart-2.2.1. 
Is it compatible? Will moving to 2.2.1 from 1.1.1 works fine?

Thanks,
Mohammed

**Comment by lvc** [comment]
See report on backward compatibility for the library: https://abi-laboratory.pro/java/tracker/timeline/json-smart/

![json-smart-1](https://user-images.githubusercontent.com/1517837/32264679-e5592c4c-bef0-11e7-8311-b699a735c4cb.png)

![json-smart-2](https://user-images.githubusercontent.com/1517837/32264678-e53dde7e-bef0-11e7-8a24-4ef53789b636.png)

**Comment by ymohdriz** [comment]
Thanks @ivc
