### ISSUE TITLE
Support LocalDate

### ISSUE THREAD

**Issue by fabienrenaud** [netplex/json-smart-v2#45]
Getting this exception from jsonsmart when trying to serialize a `LocalDate`:
java.lang.IllegalAccessError: tried to access field java.time.LocalDate.month from class net.minidev.asm.java.time.LocalDateAccAccess

For context, the contributor of dsljson added a serie of new tests to [java-json-benchmark](https://github.com/fabienrenaud/java-json-benchmark) that covers types such as `LocalDate`, `OffsetDateTime` and `UUID`... jsonsmart currently does not handle any of these 3 types,  which means it is excluded from this particular test suite, but I'd like to bring it back...

Implementing custom serializers works, but since the [docs showing how to implement a custom deserializer are missing](https://github.com/netplex/json-smart/wiki/Custom-Serialisation), I am a little stuck here...

**Comment by UrielCh** [comment]
please provide a code sample

**Comment by UrielCh** [comment]
I add `net.minidev.json.testMapping.TestUUID` and `net.minidev.json.testMapping.TestCustomMappingInstant`

maybe it can help you.
