### ISSUE TITLE
Fix maven-metadata.xml in Central repository

### ISSUE THREAD

**Issue by flopma** [netplex/json-smart-v2#52]
Hello,

I would like to report to you the issue arising when using your library.

Maven tries to download the version 2.3-SNAPSHOT and cannot from the Central repository - leading to random failures.

Can you please update that file and make it available in Central repository?

Thanks a lot for your help

**Comment by svatos-jirka** [comment]
Do you use http or https? because maven central uses https from 15. of janury 2020 only now!

**Comment by flopma** [comment]
I checked again the metadata.xml in Central and it is alright. I am not sure what is the source of the 2.3-SNAPSHOT. I will investigate further at our side. Sorry for the inconvenience. Regards
