### ISSUE TITLE
Multi-threading issue in JsonWriter

### ISSUE THREAD

**Issue by rwankar** [netplex/json-smart-v2#53]
In JsonWriter the variable writerInterfaces is defined as

` private LinkedList<WriterByInterface> writerInterfaces;`

In JsonValue.java you have the code..

    public static void writeJSONString(Object value, Appendable out, JSONStyle compression) throws IOException {
        if (value == null) {
            out.append("null");
            return;
        }
        Class<?> clz = value.getClass();
        @SuppressWarnings("rawtypes")
        JsonWriterI w = defaultWriter.getWrite(clz);
        if (w == null) {
            if (clz.isArray())
                w = JsonWriter.arrayWriter;
            else {
                w = defaultWriter.getWriterByInterface(value.getClass());
                if (w == null)
                    w = JsonWriter.beansWriterASM;
                // w = JsonWriter.beansWriter;
            }
            defaultWriter.registerWriter(w, clz);
        }
        w.writeJSONString(value, out, compression);
    }

defaultWriter is static. In a multi-threaded app, if call to getWriterByInterface returns null multiple threads could call registerWriter() and the internal LinkedList is not thread safe.

**Comment by UrielCh** [comment]
`defaultWriter` is a `json-smart` V1 retro-compatibility convenience.
it can not be thread-safe.
