### ISSUE TITLE
not able to mnv package successfully on json-smart.

### ISSUE THREAD

**Issue by wei-kumar** [netplex/json-smart-v2#55]
[ERROR] Failures:
[ERROR]   TestUtf8.testBytes:51 expected:<[à·ƒà·?à??à·?à?½ à?¢à·?à??à·?à?º]> but was:<[????? ?????]>
[INFO]
[ERROR] Tests run: 116, Failures: 1, Errors: 0, Skipped: 0

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project json-smart: There are test failures.
[ERROR]
[ERROR] Please refer to D:\json-smart-v2-master\json-smart\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.

D:\json-smart-v2-master\json-smart>mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: D:\maven\apache-maven-3.6.3\bin\..
Java version: 11.0.6, vendor: Oracle Corporation, runtime: C:\Apps\Dvlp\jdk11_64
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by UrielCh** [comment]
I have the same issue 2 days ago, and then, it has gone...

sorry.
