### ISSUE TITLE
Ability to preserve elements order on parse JSON

### ISSUE THREAD

**Issue by SuperPat45** [netplex/json-smart-v2#58]
When I parse a JSON string parameters orders are lost. Even if it doesn't matter in almost all cases, I have a use case where the order need to be preserved.

We can imagine adding a boolean to the parse method to return a new class OrderedJSONObject extending LinkedHashMap:

```
OrderedJSONObject document = JSONValue.parse(responseStr, true);
```

**Comment by UrielCh** [comment]
I think you should tell the parser that you expect a `LinkedHashMap`.
A mapper named `DefaultMapperOrdered` exists for that.

available in `JsonReader.DEFAULT_ORDERED`

**Comment by UrielCh** [comment]
after reading my code.

the function your looking for is:
JSONValue.parseKeepingOrder(text)
