### ISSUE TITLE
StackOverflowError of java.nio.file.Path as a special iterable type invoke toJSONString()

### ISSUE THREAD

**Issue by seuldos** [netplex/json-smart-v2#59]
Hello Friends!

Error is thrown when I execute the following unit test, i found that when the generic object of the iterator is another iterator obj for example `Path` and then error occur.

*About Signatures:*
`net.minidev.json.JSONValue#writeJSONString(java.lang.Object, java.lang.Appendable, net.minidev.json.JSONStyle)`
`net.minidev.json.reader.JsonWriterI#writeJSONString`

```java
@Test
    public void test() {
        Map<String, Object> cachedTable1 = new LinkedHashMap<>();
        Iterable<Path> path = Paths.get("/home");
        cachedTable1.put("1", path);
        try {
            JSONValue.toJSONString(cachedTable1);
        } catch (Error e) {
            Assertions.assertEquals("java.lang.StackOverflowError", e.getClass().getName());
        }
    }
```

**Comment by UrielCh** [comment]
duplicated #49 fixed.
