### ISSUE TITLE
Parent pom for 2.4.4 missing in Maven Central

### ISSUE THREAD

**Issue by vdzhuvinov** [netplex/json-smart-v2#69]
Thanks for the recent 2.x updates!

On trying to use the new v2.4.4 Maven aborted with the message

```
Failed to read artifact descriptor for net.minidev:json-smart:jar:2.4.4: Could not find artifact net.minidev:minidev-parent:pom:2.4.3 in central (https://repo.maven.apache.org/maven2)
```

It appears the parent POM needs to be uploaded to Central as well:

https://search.maven.org/artifact/net.minidev/minidev-parent
https://search.maven.org/artifact/net.minidev/json-smart/2.4.4/bundle

**Comment by UrielCh** [comment]
I removed modules from the parent pom.
and try to release it again.

**Comment by radarsh** [comment]
I get the same error. Please try to release a new clean version. Thank you :)

**Comment by UrielCh** [comment]
publishing V 2.4.5 is progress.

**Comment by UrielCh** [comment]
NNNNOOOOOOOO !!!!!!

**Comment by UrielCh** [comment]
Using minidev-parent 2.4.4 as the parent for json-smart 2.4.5 was intended.

I have just publish the parent, that should fix json-smart 2.4.4 too.

details:
```bash
Uploading to ossrh: https://oss.sonatype.org/service/local/staging/deploy/maven2/net/minidev/minidev-parent/2.4.4/minidev-parent-2.4.4.pom
Uploaded to ossrh: https://oss.sonatype.org/service/local/staging/deploy/maven2/net/minidev/minidev-parent/2.4.4/minidev-parent-2.4.4.pom (8.6 kB at 544 B/s)
Downloading from ossrh: https://oss.sonatype.org/service/local/staging/deploy/maven2/net/minidev/minidev-parent/maven-metadata.xml
Uploading to ossrh: https://oss.sonatype.org/service/local/staging/deploy/maven2/net/minidev/minidev-parent/maven-metadata.xml
Uploaded to ossrh: https://oss.sonatype.org/service/local/staging/deploy/maven2/net/minidev/minidev-parent/maven-metadata.xml (305 B at 199 B/s)
Uploading to ossrh: https://oss.sonatype.org/service/local/staging/deploy/maven2/net/minidev/minidev-parent/2.4.4/minidev-parent-2.4.4.pom.asc
Uploaded to ossrh: https://oss.sonatype.org/service/local/staging/deploy/maven2/net/minidev/minidev-parent/2.4.4/minidev-parent-2.4.4.pom.asc (833 B at 2.3 kB/s)
```

**Comment by goughy000** [comment]
json-smart 2.4.5 is requesting accessors-smart 2.4.3 as a dependency, however this is missing from central too

![image](https://user-images.githubusercontent.com/3418267/115363515-72fb6880-a1ba-11eb-95a5-c2af8d009477.png)


![image](https://user-images.githubusercontent.com/3418267/115363407-5b23e480-a1ba-11eb-829d-46bb0e7ba194.png)

**Comment by UrielCh** [comment]
```
Uploading to ossrh: https://oss.sonatype.org/service/local/staging/deploy/maven2/net/minidev/minidev-parent/2.4.3/minidev-parent-2.4.3.pom
Uploaded to ossrh: https://oss.sonatype.org/service/local/staging/deploy/maven2/net/minidev/minidev-parent/2.4.3/minidev-parent-2.4.3.pom (8.6 kB at 138 B/s)
Downloading from ossrh: https://oss.sonatype.org/service/local/staging/deploy/maven2/net/minidev/minidev-parent/maven-metadata.xml
Uploading to ossrh: https://oss.sonatype.org/service/local/staging/deploy/maven2/net/minidev/minidev-parent/maven-metadata.xml
Uploaded to ossrh: https://oss.sonatype.org/service/local/staging/deploy/maven2/net/minidev/minidev-parent/maven-metadata.xml (305 B at 133 B/s)
Uploading to ossrh: https://oss.sonatype.org/service/local/staging/deploy/maven2/net/minidev/minidev-parent/2.4.3/minidev-parent-2.4.3.pom.asc
Uploaded to ossrh: https://oss.sonatype.org/service/local/staging/deploy/maven2/net/minidev/minidev-parent/2.4.3/minidev-parent-2.4.3.pom.asc (833 B at 2.1 kB/s)
```

one more!

**Comment by zeldigas** [comment]
@UrielCh Does it adresses issues with version 2.4.4 or for version 2.4.5? As @goughy000 mentioned, 2.4.5 currently fails due to missing accessors-smart-2.4.2

**Comment by UrielCh** [comment]
Just tell me if it works now, I stopped java development 5 years ago.
All my projects are now written inTypescript.

**Comment by zeldigas** [comment]
@UrielCh no it does not work. Currently maven fails to `net.minidev:accessors-smart:jar:2.4.3`. 
This problem is same for both `net.minidev:json-smart:2.4.4` and `net.minidev:json-smart:2.4.5`

**Comment by UrielCh** [comment]
thx to issue #70, I have a reason to update accessors-smart.

so I will upgrade every think to V 2.5.0.

**Comment by radarsh** [comment]
@UrielCh do you have an ETA for this?

**Comment by vdzhuvinov** [comment]
Does anyone have a step by step suggestion for Uriel how to push to Maven Central the parent POMs from the previous version?
It appears to me that those POMs were deployed to his local repo only. If there is a way to push them retroactively to Maven Central we should be all fine.

**Comment by UrielCh** [comment]
What pom is missing for now? I'm a little bit lost.

**Comment by UrielCh** [comment]
from V 2.5.0 parent pom if GONE!

**Comment by UrielCh** [comment]
you have 24 hours to give feedback before I publish the current master/main branch.

the root pom.xml is now deleted.

**Comment by mmoayyed** [comment]
Switching to 2.4.5 causes the following failure:

```
Execution failed for task ':core:cas-server-core-util-api:compileJava'.
> Could not resolve all files for configuration ':core:cas-server-core-util-api:compileClasspath'.
   > Could not find net.minidev:accessors-smart:2.4.3.
     Searched in the following locations:
       - file:/Users/Misagh/.m2/repository/net/minidev/accessors-smart/2.4.3/accessors-smart-2.4.3.pom
       - https://repo.maven.apache.org/maven2/net/minidev/accessors-smart/2.4.3/accessors-smart-2.4.3.pom
       - https://oss.sonatype.org/content/repositories/releases/net/minidev/accessors-smart/2.4.3/accessors-smart-2.4.3.pom
     Required by:
         project :core:cas-server-core-util-api > net.minidev:json-smart:2.4.5
```

Is `net.minidev:accessors-smart:2.4.3` not published to central? I don't see there it.

**Comment by zeldigas** [comment]
>Does anyone have a step by step suggestion for Uriel how to push to Maven Central the parent POMs from the previous version

@UrielCh please run publishing form another artifact - `accessors-smart` for version `2.4.3`. Right now it's missing in maven central and cause build to fail. I suppose you have it configured using nexus oss plugin, so it should be possible to run deployment only for this one.

If it does not work, than I suppose the proper solution would be to do a techinical release of `2.4.6` where you'd synchronize versions for all modules, disregarding the fact if there are changes or not. You can use `mvn versions:set` plugin to assist you with bumping versions.

**Comment by UrielCh** [comment]
no problemo.

**Comment by vdzhuvinov** [comment]
With the new 2.4.6 all deps resolved successfully and compile works too.

Cheers!
