### ISSUE TITLE
2.1.0 version do not export the new packages

### ISSUE THREAD

**Issue by aborg0** [netplex/json-smart-v2#7]
It seems the reader and writer packages are supposed to be part of the API, though they are not exported in the released OSGi bundle.
An attempt to fix this problem is in the commit 7f22d7a89111cde6c5ee4bb0773037a05829be76 (part of the pull request #6, which also addresses the issue of version compatibility by re-adding the deprecated parts used by for example the jayway/json-path project).

**Comment by UrielCh** [comment]
json-smart current versions are OSGi ready.
