### ISSUE TITLE
support latest asm in accessor-smart

### ISSUE THREAD

**Issue by amergey** [netplex/json-smart-v2#70]
Currently accessor-smart depends on asm 8 which is a 1 year old release.
it should depends on 9.1 which is latest (and also to be able to use recent version other libs also based on asm)

if accessor-smart is supporting multiple asm version it should override osgi manifest as by default only asm 8 is supported

(for example by adding this instruction to maven-bundle-plugin in pom.xml)
`<Import-Package>org.objectweb.asm;version="[8.0,10),*</Import-Package>`

**Comment by UrielCh** [comment]
that a good opportunity to upgrade all version number :)

**Comment by UrielCh** [comment]
I did not use a pom.xml file for maybe 7 years,
I will be pleased to apply your changes, can you give me more detail about the changes I have to do in my maven files?

or open a PR... it's nice too. :grin:

putting:

```xml
<!-- https://mvnrepository.com/artifact/org.ow2.asm/asm -->
<dependency>
    <groupId>org.ow2.asm</groupId>
    <artifactId>asm</artifactId>
    <version>9.1</version>
</dependency>
```

In the accessors-smart pom.xml might not be the best solution.

**Comment by amergey** [comment]
Do you know if accessors-smart is able to run with with asm from 8 to 9.1 ? if it is the case then updating osgi metadata only will be the best solution
I will open a PR tomorrow

**Comment by UrielCh** [comment]
Test unit will told us :)
