### ISSUE TITLE
!!!URGENT!!! Upgrading to json-smart 2.4.5 causes missing dependency `net.minidev:accessors-smart:jar:2.4.3`

### ISSUE THREAD

**Issue by cliu123** [netplex/json-smart-v2#76]
Upgrading `json-smart` to `2.4.5` for [issue#67](https://github.com/netplex/json-smart-v2/issues/67) and [issue#10](https://github.com/netplex/json-smart-v1/issues/10). 
Forcing `json-smart` to 2.4.5 with the following:
```
            <dependency>
                <groupId>net.minidev</groupId>
                <artifactId>json-smart</artifactId>
                <version>2.4.5</version>
            </dependency>
```

But it causes the following error:
```
Failed to execute goal on project opensearch-security: Could not resolve dependencies for project org.opensearch:opensearch-security:jar:1.0.0.0-rc1: Could not find artifact net.minidev:accessors-smart:jar:2.4.3 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```
Had to force `accessors-smart` to `2.4.2` with the following to compile:
```
            <dependency>
                <groupId>net.minidev</groupId>
                <artifactId>accessors-smart</artifactId>
                <version>2.4.2</version>
            </dependency>
```
Looks like `json-smart-2.4.5` upgrades the dependency `accessors-smart` to 2.4.3, but `accessors-smart-2.4.3.jar` is unavailable in Maven Central?

**Comment by cliu123** [comment]
Regarding this PR: https://github.com/opensearch-project/security/pull/1299/files

**Comment by cliu123** [comment]
accessors-smart-2.4.3.jar is missing at [here](https://repo.maven.apache.org/maven2/net/minidev/accessors-smart/2.4.3/). But accessors-smart-2.4.2.jar is [available](https://repo.maven.apache.org/maven2/net/minidev/accessors-smart/2.4.2/). Is this expected?

**Comment by Shoothzj** [comment]
I think it's unexpected.
You can use version >= 2.4.7.
I will close this issue, feel free to reopen it
