### ISSUE TITLE
Add a constructor with size parameter on JSONArray and JSONObject classes

### ISSUE THREAD

**Issue by SuperPat45** [netplex/json-smart-v2#80]
JSONArray is initialized with an initial size of 10, but if I know in advance that I have hundreds of elements, a new constructor with an initial size can avoid lots of arraycopy under the hood.
Conversely, if I know I have less than 10 items, it could save memory.

Idem for JSONObject

**Comment by UrielCh** [comment]
Easy to improve, and should not beak anything else, feel free to open a PR, I'm okay with this change.

**Comment by Shoothzj** [comment]
@SuperPat45 @UrielCh Sorry for my late reply, I have already create PR for this.

**Comment by Shoothzj** [comment]
@SuperPat45 the PR has been merged, free feel to tell me if you want a new release
